# https://taskfile.dev
version: "3"
tasks:
  dep-sepolia: npx hardhat run scripts/deploy.ts --network sepolia
  dep-local: npx hardhat run scripts/deploy.ts
  t: REPORT_GAS=true npx hardhat test
  sh: npx hardhat console
  build: npx hardhat compile
  mint: npx hardhat run scripts/mint.ts --network sepolia
  accounts: npx hardhat accounts
  cover: npx hardhat coverage

  setup:
    cmds:
      - |
        npm init -y
        npm install --save-dev hardhat
        npx hardhat init

        npm install @openzeppelin/contracts

        npm install --save-dev @solidstate/hardhat-accounts
        npm install --save-dev hardhat-sourcify
